[WIP] UI test for creating file in project space
owncloud/moodle-repository_ocis pull request #88
Opened 2024-03-14 11:06 UTC by S-Panta

2024-03-19 09:58 UTC, individual-it requested changes

2024-03-19 09:58 UTC, individual-it commented on tests/behat/behat_repository_ocis.php
> +    }
```suggestion
    public function delete_all_project_spaces(AfterScenarioScope $scope) {
        $createdSpaces = $this->get_all_created_project_spaces();
        foreach ($createdSpaces as $space) {
            $this->delete_space();
        }
    }
```

2024-03-19 09:58 UTC, individual-it commented on tests/behat/behat_repository_ocis.php
> +    private function add_to_created_space($response) {
```suggestion
    private function add_to_created_spaces($response) {
```

2024-03-19 09:58 UTC, individual-it commented on tests/behat/behat_repository_ocis.php
> +    public function get_space_id_by_space($space): string {
```suggestion
    public function get_space_id($spaceName): string {
```

2024-03-19 09:58 UTC, individual-it commented on tests/behat/uploadFileToMoodle.feature
> +    Given "admin" creates a project space "ProjectMoodle"
```suggestion
    Given "admin" creates a project space called "ProjectMoodle"
```
Or
```suggestion
    Given "admin" creates the project space "ProjectMoodle"
```

2024-03-19 09:58 UTC, individual-it commented on tests/behat/behat_repository_ocis.php
> +     * @Given I click on Refresh button
I think its better to describe the functionality

```suggestion
     * @Given I refresh the file-picker
```

2024-03-19 09:58 UTC, individual-it commented on tests/behat/behat_repository_ocis.php
> +            $this->find('xpath', "//*[@id='oc-login-username']"), $this->get_actual_username($user),
we should do nice page-objects one day, but this is good for now

2024-03-21 04:53 UTC, individual-it requested changes

2024-03-21 04:53 UTC, individual-it commented on tests/behat/uploadFileToMoodle.feature
> +    And "admin" uploads file with content "test file" to "/testfile.txt" in "ProjectMoodle" space
In ocis API tests we are using `Given user "Alice" has uploaded a file inside space "Alice Hansen" with content "some content" to "textfile.txt"`

2024-03-22 04:21 UTC, phil-davis commented on tests/behat/behat_repository_ocis.php
> +        }
Or throw an exception so that the test crashes straight away. `get-space_id` should only be called for spaces that we already know about.

2024-03-22 04:36 UTC, phil-davis reviewed
Just a few suggestions to put more information in exception messages.

2024-03-22 04:36 UTC, phil-davis commented on tests/behat/behat_repository_ocis.php
> +            throw new Exception("Error creating resource in ocis " . var_dump($response['statusCode']));
```suggestion
            throw new Exception("Error creating resource in ocis personal space of user '$user', status was " . var_dump($response['statusCode']));
```

will it help to give more information in the exception message?

2024-03-22 04:36 UTC, phil-davis commented on tests/behat/behat_repository_ocis.php
> +            throw new Exception("Error creating resource in ocis " . var_dump($response['statusCode']));
```suggestion
            throw new Exception("Error creating resource in ocis project space '$space', status was " . var_dump($response['statusCode']));
```

will it help to give more information in the exception message?

2024-03-22 04:36 UTC, phil-davis commented on tests/behat/uploadFileToMoodle.feature
> +    And I refresh the file-picker
I don't think it matters much in a scenario like this.
We are testing that an uploaded file can be seen. To get to the "Then" step, we have to do some UI things, and they are not really the things that we are testing, they are just a way to get to "see" the uploaded file. So it hard to know if any of these steps are Given or When.

2024-03-26 06:52 UTC, individual-it approved these changes

2024-03-26 06:52 UTC, merged